// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Theoremone.SmartAc.Infrastructure.Persistence;

#nullable disable

namespace Theoremone.SmartAc.Infrastructure.Data.Migrations.Sqlite
{
    [DbContext(typeof(SmartAcContext))]
    [Migration("20220807155749_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.Device", b =>
                {
                    b.Property<string>("SerialNumber")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstRegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedSecret")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("SerialNumber");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceReading", b =>
                {
                    b.Property<int>("DeviceReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CarbonMonoxide")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Health")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Humidity")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ReceivedDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordedDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Temperature")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("DeviceReadingId");

                    b.HasIndex("DeviceSerialNumber");

                    b.ToTable("DeviceReadings");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceRegistration", b =>
                {
                    b.Property<int>("DeviceRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeviceSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceRegistrationId");

                    b.HasIndex("DeviceSerialNumber");

                    b.ToTable("DeviceRegistrations");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceReading", b =>
                {
                    b.HasOne("Theoremone.SmartAc.Data.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Theoremone.SmartAc.Data.Models.DeviceRegistration", b =>
                {
                    b.HasOne("Theoremone.SmartAc.Data.Models.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceSerialNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });
#pragma warning restore 612, 618
        }
    }
}
